---
application:
  name: "djevents-backend"
  project: "djevents-backend"
  organization: "QoveryCommunity"
  storage:
  - name: "images"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/images"
databases:
- type: "POSTGRESQL"
  name: "djevents"
  version: "11"
routers:
- name: "main-djevents-backend"
  routes:
  - application_name: "djevents-backend"
    paths:
    - "/*"
